require("dotenv").config();

export const {
  REACT_APP_API_CURRENT,
  REACT_APP_API_FORECAST,
  REACT_APP_API_APPID,
  REACT_APP_IMAGE_API,
  REACT_APP_IMAGE_API_APPID,
  REACT_APP_TRIP_API,
  REACT_APP_TRIP_API_APPID,
  REACT_APP_GOOGLE_API,
  REACT_APP_GOOGLE_API_APPID,
  REACT_APP_RAPID_IMAGE_API,
  REACT_APP_RAPID_IMAGE_API_APPID,
} = process.env;
